title: T-Watch S3
description: LILYGO®  T-Watch S3 full feature implementation for ESPHome
# theme: jekyll-theme-slate
remote_theme: riggraz/no-style-please
plugins:
- jekyll-remote-theme
google_analytics: G-5H8W7JPJW7