# https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md

title: T-Watch S3
tagline: LILYGO® T-Watch S3 ESPHome
description: LILYGO® T-Watch S3 full feature implementation for ESPHome
author:
  name: Veli-Johan Veromann
  twitter: velivelilev
  url: https://veli.ee

twitter:
  username: velivelilev

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/cover.png


#  email: your-email@domain.com

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.

# Build settings


#theme: jekyll-theme-slate
remote_theme: riggraz/no-style-please
plugins:
- jekyll-remote-theme
- jekyll-default-layout
- jekyll-gist
- jekyll-seo-tag
- jekyll-github-metadata
- jekyll-optional-front-matter
#- jekyll-paginate
#- jekyll-readme-index
- jekyll-titles-from-headings
- jekyll-relative-links
#google_analytics: G-5H8W7JPJW7
#markdown: kramdown

#lsi: false
safe: true
#source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
#  math_engine: mathjax
  syntax_highlighter: rouge
  remove_block_html_tags: false

social:
  name: Veli-Johan Veromann
  links:
    - https://twitter.com/velivelilev
    - https://www.linkedin.com/in/veliveromann
    - https://github.com/velijv


  # Generate social links in footer.
social_links:
  #  - { platform: devto,          user_url: "https://dev.to/jekyll" }
    - { platform: dribbble,       user_url: "https://dribbble.com/veli" }
  #  - { platform: facebook,       user_url: "https://www.facebook.com/jekyll" }
  #  - { platform: flickr,         user_url: "https://www.flickr.com/photos/jekyll" }
    - { platform: github,         user_url: "https://github.com/velijv" }
  #  - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
  #  - { platform: instagram,      user_url: "https://www.instagram.com/jekyll" }
  #  - { platform: keybase,        user_url: "https://keybase.io/jekyll" }
  #  - { platform: linkedin,       user_url: "https://www.linkedin.com/in/jekyll" }
  #  - { platform: microdotblog,   user_url: "https://micro.blog/jekyll" }
  #  - { platform: pinterest,      user_url: "https://www.pinterest.com/jekyll" }
  #  - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/1234567/jekyll" }
  #  - { platform: telegram,       user_url: "https://t.me/jekyll" }
  #  - { platform: twitter,        user_url: "https://twitter.com/jekyllrb" }
    - { platform: x,              user_url: "https://x.com/velivelilev" }
  #  - { platform: youtube,        user_url: "https://www.youtube.com/jekyll" }